name: Scheduled Action

on:
  schedule:
    # Run every 12 hours (at 00:00 and 12:00 UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo message
        run: echo "This action runs every 12 hours"
